services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  server:
    build: ./server
    depends_on:
      - mongo
      - redis
    ports:
      - '9999:9999'
    volumes:
      - ./server/src:/app/src
    command: node --watch src/server.js
    env_file:
      - ./server/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/attendance
      REDIS_URL: redis://redis:6379
      MONGODB_REPLICA_SET: 'false'

  client:
    build: ./client
    command: npm run dev
    ports:
      - '5173:5173'
    volumes:
      - ./client/src:/app/src
    environment:
      VITE_API_BASE_URL: http://localhost:9999/api

volumes:
  mongo_data:
