services:
  server:
    image: ghcr.io/phucttg/attendance_tracking/server:latest
    restart: unless-stopped
    env_file:
      - ./server/.env

  nginx:
    image: ghcr.io/phucttg/attendance_tracking/nginx:latest
    ports:
      - '80:80'
    depends_on:
      - server
    restart: unless-stopped
